language: php

dist: bionic
sudo: false

cache:
  directories:
    - vendor

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--prefer-lowest --prefer-stable"

php:
  - 7.2

  branches:
  only:
    - master